apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
  labels:
    app: hive-metastore
spec:
  selector:
    matchLabels:
      app: hive-metastore
  replicas: 1
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - name: hive-metastore
        image: 
          repository: sslhep/hive-metastore
          pullPolicy: IfNotPresent
          tag: "3.1.3"
        env:
        - name: HIVE_DATABASE_HOST
          value: "hive-metastore-db-service"
        - name: HIVE_DATABASE_PORT
          value: "5432"
        - name: HIVE_DATABASE_NAME
          value: "metastore_db"
        - name: HIVE_DATABASE_USER
          value: "hiveuser"
        - name: HIVE_DATABASE_PASSWORD
          value: "hivepassword"
        - name: HIVE_DATABASE_TYPE
          value: "postgresql"
        ports:
        - containerPort: 9083
