apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-db-service
  namespace: hive-metastore
spec:
  selector:
    app: hive-metastore-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
